name: "PR files guard"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-dist:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dist:
              - 'dist/**'

      - name: Comment if dist/ was changed
        if: steps.filter.outputs.dist == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚠️ **Warning!** You have made changes to the `dist/` directory. 
            These files should not be edited manually as they will be built by our CI/CD pipeline during release. 
            Please remove these changes from the pull request.
